### ISSUE TITLE
Améliorer les fonctions Fetch

### ISSUE THREAD

**Issue by jumperdenfer** [julien-buabent/auberge-espagnole#1]
- Faire en sorte que la fonction fetch ( notamment pour food) renvoie un nombre d’élément spécifié, et pas seulement un.

**Comment by animyrch** [comment]
la fonction fetch() dans ns_food.ts ne renvoie pas un seul élément par contre, il renvoie tous les éléments d'un des tableaux à l'intérieur de l'objet litteral products.

**Comment by animyrch** [comment]
D'ailleurs, je croyais qu'on n'était pas censé modifier les fichiers d'origine. Pouvez-vous confirmer ? @julien-buabent 
Si l'on peut les modifier, 
Je propose de créer deux fonctions `fetch()`

1. `fetchOne("array", "selection"?)` //, retourne l'élément "selection" du tableau. si "selection" n'est pas défini à l'appel de la fonction, un élément alétoire est retourné dans le tableau donné
2. `fetchAll ("array")` //retourne tous les éléments du tableau donné. Cela correspond à la fonction fetch() qu'on a pour le moment

**Comment by fyzalis** [comment]
En effet, dans le TP, vous n'êtes pas sensés modifier les namespaces. Mais maintenant que tout le monde a travaillé dessus, faites vous plaisir si vous voulez apporter toutes sorte de modif :)

**Comment by animyrch** [comment]
ns_food.ts est mis à jour avec une fonction fetchOne(). Vous pouvez remplacer vos opérations comme
`NS_Food.Food.fetch('tableau')[index]` =par=> `NS_Food.food.fetchOne('tableau', index)`
et surtout
`NS_Food.Food.fetch('tableau')` + fonction séparée pour obtenir un élément alétoire + appel à cette fonction =par> `NS_Food.food.fetchOne('tableau')`

Je n'ai pas touché ns_food.food.fetch() pour compatibilité retro
